version: '3'
services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - APP_PORT=${FRONTEND_PORT}
      - APP_URL_FPSAK=http://fpsak:8080
      - OIDC_HOST_URL=http://host.docker.internal:8060/rest/isso/oauth2
      - OIDC_AGENTNAME=foo
      - OIDC_PASSWORD=bar
      - REDIS_HOST=redis
    links:
      - redis
      - fpsak
    env_file:
      - ./common.list

  redis:
    image: redis

  fpmock2: # Kan erstattes med dockerhub?...
    image: ${VTP_IMAGE}
    networks:
      default:
        aliases:
          - fpmock2
    ports:
      - 8060:8060 # HTTP
      - 8389:8389 # LDAP
    environment:
      - CUSTOM_KEYSTORE_PASSWORD=changeit
      - CUSTOM_KEYSTORE_PATH=/app/testcerts/vtpkeystore.jks
      - ENABLE_CUSTOM_TRUSTSTORE=true
      - LDAP_PROVIDER_URL=ldaps://fpmock2:8636
    volumes:
      - "~/.modig/:/root/.modig"
    env_file:
      - ./common.list

  vtp-https:
    image: ${SSL_TERM_IMAGE}
    ports:
      - 8063:8063
    environment:
      - GOSSLTERM_BACKEND_ADDR=fpmock2:8060
      - GOSSLTERM_FRONTEND_ADDR=:8063

  vtp-ldaps:
    image: ${SSL_TERM_IMAGE}
    ports:
      - 8636:8636
    environment:
      - GOSSLTERM_BACKEND_ADDR=fpmock2:8389
      - GOSSLTERM_FRONTEND_ADDR=:8636

  fpsak-https:
    image: ${SSL_TERM_IMAGE}
    ports:
      - 8443:8443
    environment:
      - GOSSLTERM_BACKEND_ADDR=fpsak:8080
      - GOSSLTERM_FRONTEND_ADDR=:8443

  fpfordel:
    image: ${FORDEL_IMAGE}
    ports:
      - 8090:8090
    env_file:
      - ./common.list
    volumes:
      - "~/.modig/:/root/.modig"
    environment:
      - APP_NAME=fpfordel
      - DEFAULTDS_PASSWORD=fpfordel
      - DEFAULTDS_USERNAME=fpfordel
      - FORELDREPENGER_STARTDATO=2017-01-01
      - LOADBALANCER_FQDN=localhost:8090
      - LOGBACK_CONFIG=./conf/logback-dev.xml
      - SERVER_PORT=8090
      - MOTTAK_QUEUE_QUEUEMANAGER=mq://e26apvl121.test.local:1411/MUXLSC01
      - MOTTAK_QUEUE_QUEUENAME=QA.U87_FPSAK_SSL.MOTTAK_QUEUE

#  fplos:
#    image: ${LOS_IMAGE}
#    ports:
#      - 8070:8080
#    env_file:
#      - ./common.list
#    volumes:
#      - testcerts:/app/testcerts
#    environment:
#      - APP_NAME=fplos
#      - DEFAULTDS_PASSWORD=fplos
#      - DEFAULTDS_USERNAME=fplos
#      - KAFKA_AKSJONSPUNKTHENDELSE_CLIENT_ID=fplos
#      - KAFKA_AKSJONSPUNKTHENDELSE_GROUP_ID=fplos
#      - LOADBALANCER_FQDN=localhost:8070


  fpsak:
    image: ${FPSAK_IMAGE}
    restart: on-failure
    env_file:
      - ./common.list
    links:
      - fpsak-oracle
      - fpmock2
    ports:
      - 8080:8080
    volumes:
      - "~/.modig/:/root/.modig"
    environment:
      - APP_NAME=fpsak
      - DEFAULTDS_PASSWORD=fpsak
      - DEFAULTDS_USERNAME=fpsak
      - DVHDS_PASSWORD=fpsak_hist
      - DVHDS_URL=jdbc:oracle:thin:@fpsak-oracle:1521/XE
      - DVHDS_USERNAME=fpsak_hist
      - EXTRA_CLASS_PATH=:vtp-lib/*
      - FP_TILKJENTYTELSE_V1_TOPIC_URL=privat-foreldrepenger-tilkjentytelse-v1-t4
      - FPSAK_CHANNEL_NAME=U87_FPSAK_SSL
      - FPSAK_CHANNEL_QUEUEMANAGER=mq://e26apvl121.test.local:1411/MUXLSC01
      - FPSAK_OKONOMI_OPPDRAG_MOTTAK_QUEUEMANAGER=mq://vtpmq:1414/QM1
      - FPSAK_OKONOMI_OPPDRAG_MOTTAK_QUEUENAME=VTP.OKONOMI.INN
      - FPSAK_OKONOMI_OPPDRAG_SEND_QUEUENAME=VTP.OKONOMI.UT
      - KAFKA_AKSJONSPUNKTHENDELSE_CLIENT_ID=fpsak
      - KAFKA_AKSJONSPUNKTHENDELSE_GROUP_ID=fpsak
      - KAFKA_RISIKOKLASSIFISERING_CLIENT_ID=fpsak
      - KAFKA_RISIKOKLASSIFISERING_GROUP_ID=fpsak
      - LOADBALANCER_FQDN=localhost:8080
      - LOGBACK_CONFIG=/app/vtp-lib/logback-dev.xml
      - RAY_AVSTEM_DATA_QUEUENAME=DEV.QUEUE.1
      - SBEH_SAKSBEHANDLING_QUEUENAME=QA.U_SAKOGBEHANDLING.SAKSBEHANDLING

  fpsak-oracle:
    image: ${ORACLE_IMAGE}
    ports:
      - 1521:1521


